// Code generated by "stringer -type event -trimprefix event"; DO NOT EDIT.

package loading

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[eventStart-0]
	_ = x[eventIDs-1]
	_ = x[eventBlock-2]
	_ = x[eventTick-3]
	_ = x[eventTimeout-4]
	_ = x[eventQueueReady-5]
}

const _event_name = "StartIDsBlockTickTimeoutQueueReady"

var _event_index = [...]uint8{0, 5, 8, 13, 17, 24, 34}

func (i event) String() string {
	if i < 0 || i >= event(len(_event_index)-1) {
		return "event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _event_name[_event_index[i]:_event_index[i+1]]
}
