// Code generated by "stringer -type state -trimprefix state"; DO NOT EDIT.

package loading

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateIdle-0]
	_ = x[stateWaitingForIDs-1]
	_ = x[stateWaitingForBlocks-2]
	_ = x[stateDone-3]
}

const _state_name = "IdleWaitingForIDsWaitingForBlocksDone"

var _state_index = [...]uint8{0, 4, 17, 33, 37}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
