// Code generated by "stringer -type State -trimprefix Peer"; DO NOT EDIT.

package peers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PeerUnknown-0]
	_ = x[PeerConnected-1]
	_ = x[PeerHostile-2]
}

const _State_name = "UnknownConnectedHostile"

var _State_index = [...]uint8{0, 7, 16, 23}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
